Fix: página de erro duplicada
DevStartGame/rest-countries-api pull request #20
Opened 2023-07-25 13:49 UTC by eriveltondasilva

Task: https://trello.com/c/pPHEhTCO

2023-07-25 14:28 UTC, derciojds commented on src/pages/Error/styles.module.scss
> +    color: var(--blue-700);
Use a variável `--text-primary` para que a  cor seja dinâmica ao trocar de tema.

2023-07-25 14:34 UTC, derciojds requested changes
Tudo em ordem. 
Apenas precisa trocar as cores de texto para as variáveis com prefixo `--text-*` e a cor do botão para `--elevation-*` para que a cor seja dinâmica ao trocar de tema.

Os nomes dessas variáveis estão no arquivo `global.scss`.

2023-07-25 14:36 UTC, derciojds commented
> Tudo em ordem. Apenas precisa trocar as cores de texto para as variáveis com prefixo `--text-*` e a cor do botão para `--elevation-*` para que a cor seja dinâmica ao trocar de tema.
> 
> Os nomes dessas variáveis estão no arquivo `global.scss`.

Essa observação é para o css da página de erro

2023-07-25 14:53 UTC, eriveltondasilva commented
> > Tudo em ordem. Apenas precisa trocar as cores de texto para as variáveis com prefixo `--text-*` e a cor do botão para `--elevation-*` para que a cor seja dinâmica ao trocar de tema.
> > Os nomes dessas variáveis estão no arquivo `global.scss`.
> 
> Essa observação é para o css da página de erro

Vou revisar isso

2023-07-26 11:38 UTC, eriveltondasilva commented
> > > Tudo em ordem. Apenas precisa trocar as cores de texto para as variáveis com prefixo `--text-*` e a cor do botão para `--elevation-*` para que a cor seja dinâmica ao trocar de tema.
> > > Os nomes dessas variáveis estão no arquivo `global.scss`.
> > 
> > 
> > Essa observação é para o css da página de erro
> 
> Vou revisar isso

Auterações feitas

2023-07-26 12:17 UTC, derciojds approved these changes

2023-07-26 12:18 UTC, merged